extends Node

# Coverage Reporter Prototype
# Generates HTML coverage reports from analyzed coverage data

## HTML Generation Functions

static func generate_summary_html(coverage_data: Dictionary) -> String:
	"""
	Generate HTML summary table for all files.
	Input: Result from aggregate_total_coverage()
	Returns: HTML string
	"""
	var html = PackedStringArray()
	
	# Header
	html.append("<!DOCTYPE html>")
	html.append("<html>")
	html.append("<head>")
	html.append("  <meta charset='utf-8'>")
	html.append("  <title>Coverage Report</title>")
	html.append("  <style>")
	html.append("    body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }")
	html.append("    h1 { color: #333; }")
	html.append("    .summary { background: white; padding: 20px; border-radius: 5px; margin-bottom: 20px; }")
	html.append("    .total { font-size: 24px; font-weight: bold; margin: 15px 0; }")
	html.append("    .good { color: #28a745; }")
	html.append("    .ok { color: #ffc107; }")
	html.append("    .bad { color: #dc3545; }")
	html.append("    table { width: 100%; border-collapse: collapse; background: white; }")
	html.append("    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }")
	html.append("    th { background: #007bff; color: white; font-weight: bold; }")
	html.append("    tr:hover { background: #f8f9fa; }")
	html.append("    .percent { font-weight: bold; }")
	html.append("    .bar { height: 20px; background: #e9ecef; border-radius: 3px; overflow: hidden; }")
	html.append("    .bar-fill { height: 100%; transition: width 0.3s; }")
	html.append("  </style>")
	html.append("</head>")
	html.append("<body>")
	
	# Title
	html.append("  <h1>📊 Code Coverage Report</h1>")
	
	# Summary box
	var total_percent = coverage_data.get("percent", 0.0)
	var coverage_class = _get_coverage_class(total_percent)
	html.append("  <div class='summary'>")
	html.append("    <div class='total'>")
	html.append("      Total Coverage: <span class='%s'>%.1f%%</span>" % [coverage_class, total_percent])
	html.append("    </div>")
	html.append("    <p>%d / %d lines covered</p>" % [
		coverage_data.get("covered", 0),
		coverage_data.get("total", 0)
	])
	
	# Visual bar
	var bar_color = _get_bar_color(total_percent)
	html.append("    <div class='bar'>")
	html.append("      <div class='bar-fill' style='width: %.1f%%; background: %s;'></div>" % [
		total_percent, bar_color
	])
	html.append("    </div>")
	html.append("  </div>")
	
	# File table
	html.append("  <h2>Coverage by File</h2>")
	html.append("  <table>")
	html.append("    <thead>")
	html.append("      <tr>")
	html.append("        <th>File</th>")
	html.append("        <th>Coverage</th>")
	html.append("        <th>Lines</th>")
	html.append("        <th>Visual</th>")
	html.append("      </tr>")
	html.append("    </thead>")
	html.append("    <tbody>")
	
	# File rows
	var files = coverage_data.get("files", [])
	for file_info in files:
		var file_name = file_info.get("file", "unknown")
		var file_percent = file_info.get("percent", 0.0)
		var file_covered = file_info.get("covered", 0)
		var file_total = file_info.get("total", 0)
		var file_class = _get_coverage_class(file_percent)
		var file_bar_color = _get_bar_color(file_percent)
		
		html.append("      <tr>")
		html.append("        <td><strong>%s</strong></td>" % file_name)
		html.append("        <td class='percent %s'>%.1f%%</td>" % [file_class, file_percent])
		html.append("        <td>%d / %d</td>" % [file_covered, file_total])
		html.append("        <td>")
		html.append("          <div class='bar'>")
		html.append("            <div class='bar-fill' style='width: %.1f%%; background: %s;'></div>" % [
			file_percent, file_bar_color
		])
		html.append("          </div>")
		html.append("        </td>")
		html.append("      </tr>")
	
	html.append("    </tbody>")
	html.append("  </table>")
	
	# Footer
	html.append("  <p style='margin-top: 30px; color: #666; font-size: 12px;'>")
	html.append("    Generated by GDSentry Coverage (Spike 2 Prototype)")
	html.append("  </p>")
	html.append("</body>")
	html.append("</html>")
	
	return "\n".join(html)


static func generate_file_html(file_path: String, line_data: Dictionary, source_lines: Array) -> String:
	"""
	Generate HTML for line-by-line coverage view of a single file.
	Input: 
	  - file_path: Name of the file
	  - line_data: { line_num: hit_count } dictionary
	  - source_lines: Array of source code lines (mock data)
	Returns: HTML string
	"""
	var html = PackedStringArray()
	
	html.append("<!DOCTYPE html>")
	html.append("<html>")
	html.append("<head>")
	html.append("  <meta charset='utf-8'>")
	html.append("  <title>%s - Coverage</title>" % file_path)
	html.append("  <style>")
	html.append("    body { font-family: 'Courier New', monospace; margin: 20px; background: #f5f5f5; }")
	html.append("    h1 { font-family: Arial; color: #333; }")
	html.append("    .line { display: flex; border-bottom: 1px solid #eee; }")
	html.append("    .line-num { background: #e9ecef; padding: 4px 10px; width: 60px; text-align: right; color: #666; }")
	html.append("    .hit-count { background: #d1ecf1; padding: 4px 10px; width: 50px; text-align: center; font-weight: bold; }")
	html.append("    .source { background: white; padding: 4px 10px; flex: 1; white-space: pre; }")
	html.append("    .hit { background: #d4edda; }")
	html.append("    .miss { background: #f8d7da; }")
	html.append("    .hit .hit-count { background: #28a745; color: white; }")
	html.append("    .miss .hit-count { background: #dc3545; color: white; }")
	html.append("  </style>")
	html.append("</head>")
	html.append("<body>")
	html.append("  <h1>📄 %s</h1>" % file_path)
	
	# Line by line
	for i in range(source_lines.size()):
		var line_num = i + 1
		var hit_count = line_data.get(line_num, 0)
		var source = source_lines[i]
		var status_class = "hit" if hit_count > 0 else "miss"
		var hit_display = str(hit_count) if hit_count > 0 else "0"
		
		html.append("  <div class='line %s'>" % status_class)
		html.append("    <div class='line-num'>%d</div>" % line_num)
		html.append("    <div class='hit-count'>%s</div>" % hit_display)
		html.append("    <div class='source'>%s</div>" % _html_escape(source))
		html.append("  </div>")
	
	html.append("</body>")
	html.append("</html>")
	
	return "\n".join(html)


## Helper Functions

static func _get_coverage_class(percent: float) -> String:
	"""Get CSS class based on coverage percentage"""
	if percent >= 80.0:
		return "good"
	elif percent >= 50.0:
		return "ok"
	else:
		return "bad"


static func _get_bar_color(percent: float) -> String:
	"""Get color for progress bar based on coverage percentage"""
	if percent >= 80.0:
		return "#28a745"  # Green
	elif percent >= 50.0:
		return "#ffc107"  # Yellow
	else:
		return "#dc3545"  # Red


static func _html_escape(text: String) -> String:
	"""Escape HTML special characters"""
	return text.replace("&", "&amp;") \
	           .replace("<", "&lt;") \
	           .replace(">", "&gt;") \
	           .replace("\"", "&quot;") \
	           .replace("'", "&#39;")


## File I/O

static func write_html_file(file_path: String, html_content: String) -> bool:
	"""
	Write HTML content to file.
	Returns: true if successful, false otherwise
	"""
	# Create directory if it doesn't exist
	var dir = file_path.get_base_dir()
	if not DirAccess.dir_exists_absolute(dir):
		var err = DirAccess.make_dir_recursive_absolute(dir)
		if err != OK:
			print("ERROR: Failed to create directory: %s" % dir)
			return false
	
	# Write file
	var file = FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		print("ERROR: Failed to open file for writing: %s" % file_path)
		return false
	
	file.store_string(html_content)
	file.close()
	
	return true
