"""Project initialization."""

from pathlib import Path

import typer

from gdsentry.core.exceptions import GDSentryError


class InitializationError(GDSentryError):
    """Raised when project initialization fails."""

    pass


class ProjectInitializer:
    """
    Initializes a GDSentry project.

    Creates:
    - Configuration file (gdsentry.toml)
    - Test directories
    - Example test files
    - README
    """

    def __init__(self, init_root: Path):
        """
        Initialize project initializer.

        Args:
            init_root: Root directory for project initialization directory
        """
        self.init_root = init_root

    def initialize(
        self,
        project_name: str,
        godot_version: str = "4.2.2-stable",
        interactive: bool = False,
    ) -> None:
        """
        Initialize a new GDSentry project.

        Args:
            project_name: Project name
            godot_version: Godot version
            interactive: Whether to prompt for configuration

        Raises:
            InitializationError: If initialization fails
        """
        # Interactive prompts
        if interactive:
            project_name = typer.prompt("Project name", default=project_name)
            godot_version = typer.prompt("Godot version", default=godot_version)

        # Create configuration
        self._create_config(project_name, godot_version)

        # Create directories
        self._create_directories()

        # Create example test
        self._create_example_test()

        # Create README
        self._create_readme(project_name)

    def _create_config(self, project_name: str, godot_version: str) -> None:
        """Create gdsentry.toml configuration file."""
        config_file = self.init_root / "gdsentry.toml"

        if config_file.exists():
            raise InitializationError(
                f"Configuration file already exists: {config_file}\n"
                "Remove it or use a different directory."
            )

        config_content = f"""# GDSentry Configuration
# Generated by gdsentry init

[project]
name = "{project_name}"
godot_version = "{godot_version}"
project_root = "."

[test]
scope = "project"
filter = "*"
parallel = false
timeout = 300
watch = false
verbose = false

[platform]
default_architecture = "auto"
supported_architectures = ["x86_64", "arm64"]
qemu_enabled = false

[container]
registry = "localhost"
base_image = "gdsentry-base"
auto_build = false
auto_cleanup = true

[validation]
enabled = true
check_syntax = true
check_imports = true
check_licenses = true
quick_checks = ["gdscript", "imports"]
fail_fast = false

[docs]
format = "html"
theme = "sphinx_rtd_theme"
auto_build = false

[ci]
enabled = false
platforms = ["x86_64"]
godot_versions = ["{godot_version}"]
"""

        config_file.write_text(config_content)

    def _create_directories(self) -> None:
        """Create test directory structure."""
        directories = [
            "tests",
            "tests/unit",
            "tests/integration",
            "tests/performance",
        ]

        for directory in directories:
            dir_path = self.init_root / directory
            dir_path.mkdir(parents=True, exist_ok=True)

    def _create_example_test(self) -> None:
        """Create an example test file."""
        test_file = self.init_root / "tests" / "example_test.gd"

        test_content = """# Example GDSentry Test
# This is a sample test to get you started with GDSentry

extends GDTest

class_name ExampleTest

# ------------------------------------------------------------------------------
# TEST METADATA
# ------------------------------------------------------------------------------
func _ready() -> void:
\ttest_description = "Example test demonstrating GDSentry features"
\ttest_tags = ["example", "demo"]
\ttest_priority = "normal"
\ttest_category = "examples"

# ------------------------------------------------------------------------------
# TEST SUITE
# ------------------------------------------------------------------------------
func run_test_suite() -> void:
\t\"\"\"Run all tests in this suite\"\"\"
\trun_test("test_basic_assertion", func(): return test_basic_assertion())
\trun_test("test_equality", func(): return test_equality())
\trun_test("test_collections", func(): return test_collections())

# ------------------------------------------------------------------------------
# INDIVIDUAL TESTS
# ------------------------------------------------------------------------------
func test_basic_assertion() -> bool:
\t\"\"\"Test basic true/false assertions\"\"\"
\tassert_true(true, "True should be true")
\tassert_false(false, "False should be false")
\treturn true

func test_equality() -> bool:
\t\"\"\"Test equality assertions\"\"\"
\tassert_equals(1 + 1, 2, "Math works")
\tassert_not_equals(1, 2, "Numbers are different")
\treturn true

func test_collections() -> bool:
\t\"\"\"Test collection assertions\"\"\"
\tvar array = [1, 2, 3]
\tassert_not_empty(array, "Array is not empty")
\tassert_contains(array, 2, "Array contains 2")
\treturn true
"""

        test_file.write_text(test_content)

    def _create_readme(self, project_name: str) -> None:
        """Create GDSentry README."""
        readme_file = self.init_root / "GDSENTRY_README.md"

        readme_content = f"""# {project_name} - GDSentry Testing

This project uses GDSentry for testing.

## Quick Start

### Discover Tests

```bash
gdsentry test discover
```

### Run Tests

```bash
gdsentry test run
```

### Validate Code

```bash
gdsentry validate all
```

### Build Documentation

```bash
gdsentry docs build
```

## Configuration

Edit `gdsentry.toml` to customize your testing setup.

## Directory Structure

```
tests/
├── unit/           # Unit tests
├── integration/    # Integration tests
└── performance/    # Performance tests
```

## Learn More

- [GDSentry Documentation](https://gdsentry.readthedocs.io)
- [Getting Started Guide](https://gdsentry.readthedocs.io/getting-started)
- [API Reference](https://gdsentry.readthedocs.io/api-reference)

## Common Commands

```bash
# Run specific category
gdsentry test run --category integration

# Watch mode (TDD)
gdsentry test run --watch

# Validate before commit
gdsentry validate all

# Serve docs locally
gdsentry docs serve
```
"""

        readme_file.write_text(readme_content)

    def get_created_files(self) -> list[Path]:
        """Get list of created files."""
        return [
            self.init_root / "gdsentry.toml",
            self.init_root / "GDSENTRY_README.md",
            self.init_root / "tests" / "example_test.gd",
        ]

